### ISSUE TITLE
Managed trigger for setting "modified by", equivalent to moddatetime

### ISSUE THREAD

**Issue by olirice** [supabase/supautils#30]
# Feature request

A managed trigger equivalent to `moddatetime` (discussed in supabase/supabase#379) to populate the UUID of the auth'd user making a modification on update/insert.

## Describe the solution you'd like

Longer term I agree with @peachp's comment [here](https://github.com/supabase/supabase/issues/379#issuecomment-756037521) that a fake/wrapped data type in the UI would be a great experience.

In the meantime though, the same solution of a pre-installed trigger with a usage example as a SQL snippet would be a good stop-gap.

## Describe alternatives you've considered

Manually writing a trigger

## Implementation

Here is a possible implementation that matches the interface of `moddatetime`

```sql
-----------
-- SETUP --
-----------

CREATE EXTENSION IF NOT EXISTS hstore;

------------------------------------------------------
-- Generic Trigger Setting Modified From auth.uid() --
------------------------------------------------------

CREATE OR REPLACE FUNCTION modupdatedby() RETURNS TRIGGER AS $$
DECLARE
	auth_uid uuid = auth.uid();
BEGIN
	/*
		Notes:
			1. #= is an accessor method from the HSTORE extension that allows
			   us to set a column's value on a using a column's name as a string.
			 
			2. Trigger functions do not allow parameters in their signature
			   but passed arguments are available in an array TG_ARGV
	*/
    NEW := NEW #= format('"%s"=>%s', TG_ARGV[0], auth_uid)::hstore;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
```

Applying that trigger to a table:
```sql
-----------
-- Usage --
-----------

CREATE TABLE account(
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	updated_by UUID
);

CREATE TRIGGER handle_modified_by BEFORE INSERT OR UPDATE ON account
FOR EACH ROW EXECUTE PROCEDURE modupdatedby (updated_by);
```

And the result, with an automatically set "updated_by" field:
```sql
-------------
-- Outcome --
-------------

BEGIN;
	-- Set the auth claim to simulate an API user doing an insert
	SELECT set_config('request.jwt.claim.sub', '3b1f3a8d-ad89-4dab-902a-0d8b68db23f2', true);
	
	INSERT INTO account(name)
	VALUES ('oliver');
COMMIT;

SELECT * FROM account

------------------------------
-- id, name,     updated_by --
------------------------------
-- 1, "oliver", "3b1f3a8d-ad89-4dab-902a-0d8b68db23f2"
```

**Comment by davidchalifoux** [comment]
For anyone else stumbling upon this thread:
I tried using your function @olirice, but it caused errors when making changes not as a "user" such as from the Supabase table editor because `auth.uid()` is null.

I ended up rewriting the function so it checks this case:
```SQL
CREATE OR REPLACE FUNCTION update_updated_by() RETURNS TRIGGER AS
$$
DECLARE
    auth_uid uuid = auth.uid();
BEGIN

    IF auth_uid IS NOT NULL THEN
        NEW.updated_by = auth_uid;
        RETURN NEW;
    END IF;

    NEW.updated_by = null;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
```

I'm new to working with plpgsql, so let me know if I'm doing anything dumb.

**Comment by steve-chavez** [comment]
We've had issues on the supabase platform with the [supautils stdlib](https://supabase.github.io/supautils/standard_library/) (removed on https://github.com/supabase/supautils/pull/41). Basically relying on database objects makes restores harder since they require migrations.

(for Supabase team members, see this [supabase internal slack thread](https://supabase.slack.com/archives/C01D6TWFFFW/p1701142838705499?thread_ts=1701092064.580629&cid=C01D6TWFFFW))

Since supautils is focused on security, I don't think we should add database objects and we should only rely on "hooks" (I've made this explicit on the [README](https://github.com/supabase/supautils#supautils)).

So will close this.

(Improving DX of common operations is a good idea though, but should be on another extension).
